version: '3.9'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
  redis:
    image: 'redis:latest'
  api:
    depends_on:
      - postgres
      - redis
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /home/node/app/server/node_modules
      - ./server:/home/node/app/server
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPORT=5432
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /home/node/app/client/node_modules
      - ./client:/home/node/app/client
  worker:
    restart: always
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - /home/node/app/worker/node_modules
      - ./worker:/home/node/app/worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - '80:80'